version: "3"

services:
  app-react:
    build:
      context: ./app-react/
      dockerfile: ./Dockerfile
    container_name: "app-react"
    ports:
      - 8000:80
  app-vue:
    build:
      context: ./app-vue/
      dockerfile: ./Dockerfile
    container_name: "app-vue"
    ports:
      - 8001:80
  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
