import {
  Button,
  chakra,
  Stat,
  StatLabel,
  StatNumber,
  VStack,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCountValue, useIncrement10Count } from "../hooks/useCount";

const Page: NextPage = () => {
  const count = useCountValue();
  const increment = useIncrement10Count();

  return (
    <VStack
      minH="100vh"
      h="100vh"
      w="50%"
      px="0.5rem"
      py="0"
      mx="auto"
      spacing="2rem"
      justifyContent="center"
      alignItems="center"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <chakra.h1 fontSize="6xl" fontWeight="600">
        State Sharing
      </chakra.h1>
      <Link href="/" passHref>
        <Button as="a">BACK TO /</Button>
      </Link>
      <VStack width="50%">
        <Stat>
          <StatLabel>Recoil count</StatLabel>
          <StatNumber display="block" textAlign="center" fontSize="6xl">
            {count}
          </StatNumber>
        </Stat>
        <Button onClick={increment} mx="auto">
          +1
        </Button>
      </VStack>
    </VStack>
  );
};

export default Page;
